### PR TITLE
add scroll function

### PR DESCRIPTION
**Pull request by iquicktest**
Hi guys, I add a scroll function into this fantastic project. Please have a look at this. Any problem let me know.

### CODE REVIEW

**Comment by codeskyblue** [comment]
Also remember to complete README part, donot forget to star this project.

**Comment by codeskyblue** [comment]
There is also a relevent issue of WDA, record here: [scroll element into view before clicking it 230](https://github.com/facebook/WebDriverAgent/pull/230)

**Comment by iquicktest** [comment]
Star-ed . Heihei, Yes, I also find this issue before.  Actually it should be able to scroll to specific element before trying to click element which need be displayed by scrolling.  :-)

**Comment by codeskyblue** [comment]
Check the new code, I change the `name` to `text`

**Pull request merged**
